//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer.MirthWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ws.connectors.connect.mirth.com/", ConfigurationName="MirthWS.DefaultAcceptMessage")]
    public interface DefaultAcceptMessage {
        
        // CODEGEN: Generating message contract since element name arg0 from namespace  is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        DataAccessLayer.MirthWS.acceptMessageResponse acceptMessage(DataAccessLayer.MirthWS.acceptMessageRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<DataAccessLayer.MirthWS.acceptMessageResponse> acceptMessageAsync(DataAccessLayer.MirthWS.acceptMessageRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class acceptMessageRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="acceptMessage", Namespace="http://ws.connectors.connect.mirth.com/", Order=0)]
        public DataAccessLayer.MirthWS.acceptMessageRequestBody Body;
        
        public acceptMessageRequest() {
        }
        
        public acceptMessageRequest(DataAccessLayer.MirthWS.acceptMessageRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class acceptMessageRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string arg0;
        
        public acceptMessageRequestBody() {
        }
        
        public acceptMessageRequestBody(string arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class acceptMessageResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="acceptMessageResponse", Namespace="http://ws.connectors.connect.mirth.com/", Order=0)]
        public DataAccessLayer.MirthWS.acceptMessageResponseBody Body;
        
        public acceptMessageResponse() {
        }
        
        public acceptMessageResponse(DataAccessLayer.MirthWS.acceptMessageResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class acceptMessageResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public acceptMessageResponseBody() {
        }
        
        public acceptMessageResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface DefaultAcceptMessageChannel : DataAccessLayer.MirthWS.DefaultAcceptMessage, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DefaultAcceptMessageClient : System.ServiceModel.ClientBase<DataAccessLayer.MirthWS.DefaultAcceptMessage>, DataAccessLayer.MirthWS.DefaultAcceptMessage {
        
        public DefaultAcceptMessageClient() {
        }
        
        public DefaultAcceptMessageClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DefaultAcceptMessageClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DefaultAcceptMessageClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DefaultAcceptMessageClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DataAccessLayer.MirthWS.acceptMessageResponse DataAccessLayer.MirthWS.DefaultAcceptMessage.acceptMessage(DataAccessLayer.MirthWS.acceptMessageRequest request) {
            return base.Channel.acceptMessage(request);
        }
        
        public string acceptMessage(string arg0) {
            DataAccessLayer.MirthWS.acceptMessageRequest inValue = new DataAccessLayer.MirthWS.acceptMessageRequest();
            inValue.Body = new DataAccessLayer.MirthWS.acceptMessageRequestBody();
            inValue.Body.arg0 = arg0;
            DataAccessLayer.MirthWS.acceptMessageResponse retVal = ((DataAccessLayer.MirthWS.DefaultAcceptMessage)(this)).acceptMessage(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DataAccessLayer.MirthWS.acceptMessageResponse> DataAccessLayer.MirthWS.DefaultAcceptMessage.acceptMessageAsync(DataAccessLayer.MirthWS.acceptMessageRequest request) {
            return base.Channel.acceptMessageAsync(request);
        }
        
        public System.Threading.Tasks.Task<DataAccessLayer.MirthWS.acceptMessageResponse> acceptMessageAsync(string arg0) {
            DataAccessLayer.MirthWS.acceptMessageRequest inValue = new DataAccessLayer.MirthWS.acceptMessageRequest();
            inValue.Body = new DataAccessLayer.MirthWS.acceptMessageRequestBody();
            inValue.Body.arg0 = arg0;
            return ((DataAccessLayer.MirthWS.DefaultAcceptMessage)(this)).acceptMessageAsync(inValue);
        }
    }
}
